# virtual machine - a pretend comp
# container - a pretend computer - that is based on the existing comp that is running it
# docker is an easy way to manage a container
# docker compose - an easy way to manage multiple docker containers
# version for docker compose
version: '3'

# list of containers (a service means a container)
services:
  # the name of this service
  mydb:
    # file - an entry in a filesystem that stores data
    # file system - a way to store files on a harddrive
    # image - a file representation of a file system
    image: 'postgres:latest'
    # now we can access localhost:5432 -> container:5432 -> postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    # map a folder on our computer to a folder on the container
    volumes:
      - ./db-data:/var/lib/postgresql/data/
